version: '3'
services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile

    ports:
      - "8000:8000" # http
    links:
      - db

    environment:
      SRV_PASSWD: "123456!"
      SRV_PROTO: "http"
      SQL_ROOT_PASSWD: "test" # used to access database
      SQL_HOST: "db" # used to connect to another sql docker

      # SRV_BASE_PATH: "exam.ple/foo/bar"

    volumes:
      - ./src:/src
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
      - ./data:/var/lib/mysql
