CREATE TABLE IF NOT EXISTS urltable (
    s_key CHAR(5) PRIMARY KEY COMMENT 'ShortURL key',
    r_url VARCHAR(1024) NOT NULL COMMENT 'Real URL',
    m_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time'
);